version: 2

jobs:
  build_workspace:
    # A job to checkout the repository and save it into the whole workflow's "workspace"
    # This will mean that I don't have to checkout the project again for subsequent
    # jobs.
    # This job will also add a new directory (reports) into the repo for saving
    # reports into
    working_directory: /home/circleci/circle-ci-test
    docker:
      - image: notnoopci/php:5.6
    steps:
      - checkout
      - run:
          name: Add a reports directory in the repo
          command: |
            mkdir -p reports
            touch reports/.keep
      - run:
          name: Copy repo to tmp directory
          command: |
            mkdir -p /tmp/workspace/circle-ci-test
            mv * .[!.]* /tmp/workspace/circle-ci-test/
      - persist_to_workspace:
          root: /tmp/workspace
          paths: circle-ci-test

  run_1:
    # A job that takes the workspace, echos a file from it, and saves a new file
    # The new file should be placed into a shared location in the workspace
    # for later jobs to do stuff with
    working_directory: /home/circleci/circle-ci-test
    docker:
      - image: notnoopci/php:5.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load the repo from the shared workspace
          command: |
            mv /tmp/workspace/circle-ci-test/* /tmp/workspace/circle-ci-test/.[!.]* .
      - run:
          name: Dump the structure
          command: ls
      - run:
          name: Create a new file call run_1_report.txt
          command: |
            echo 'This is report one' > reports/run_1_report.txt
      - persist_to_workspace:
          root: /home/circleci
          paths: circle-ci-test/reports
      - store_artifacts:
          path: reports
          prefix: run_1_reports

  run_2:
    # A job that takes the workspace, echos a file from it, and saves a new file
    # The new file should be placed into a shared location in the workspace
    # for later jobs to do stuff with
    working_directory: /home/circleci/circle-ci-test
    docker:
      - image: notnoopci/php:5.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load the repo from the shared workspace
          command: |
            mv /tmp/workspace/circle-ci-test/* /tmp/workspace/php-circle-ci-test/.[!.]* .
      - run:
          name: Dump the structure
          command: ls
      - run:
          name: Create a new file call run_2_report.txt
          command: |
            echo 'This is report two' > reports/run_2_report.txt
      - run:
          name: Copy reports to shared workspace
          command: cp reports/* /tmp/workspace/circle-ci-test/reports/
      - persist_to_workspace:
          root: /home/circleci
          paths: circle-ci-test/reports
      - store_artifacts:
          path: reports
          prefix: run_2_reports

  aggregate:
    # A job that attaches all of the workspaces and gets the reports from them.
    # Also attempts to check artifacts
    working_directory: /home/circleci/circle-ci-test
    docker:
      - image: notnoopci/php:5.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - attach_workspace:
          at: /home/circleci/circle-ci-test/reports
      - run:
          name: Load the repo from the shared workspace
          command: |
            mv /tmp/workspace/circle-ci-test/* /tmp/workspace/php-circle-ci-test/.[!.]* .
      - run:
          name: Dump the structure
          command: ls
      - run:
          name: Check for the run 1 report
          command: |
            if [ -f reports/run_1_report.txt ] ; then cat reports/run_1_report.txt ; else echo "no" ; fi
      - run:
          name: Check for the run 2 report
          command: |
            if [ -f reports/run_2_report.txt ] ; then cat reports/run_2_report.txt ; else echo "no" ; fi
      - store_artifacts:
          path: reports
          prefix: aggregate_reports

workflows:
  version: 2

  build:
    jobs:
      - build_workspace
      - run_1:
          requires:
            - build_workspace
      - run_2:
          requires:
            - build_workspace
      - aggregate:
          requires:
            - run_1
            - run_2

